services:

    CoreShop\Bundle\OptimisticEntityLockBundle\Manager\EntityLockManagerInterface: '@CoreShop\Bundle\OptimisticEntityLockBundle\Manager\EntityLockManager'
    CoreShop\Bundle\OptimisticEntityLockBundle\Manager\EntityLockManager: ~

    CoreShop\Bundle\OptimisticEntityLockBundle\EventListener\LockListener:
        arguments:
            - '@CoreShop\Bundle\OptimisticEntityLockBundle\Manager\EntityLockManager'
        tags:
            - { name: kernel.event_subscriber }
